apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bxkz5p09y-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bxkz5p09y-go 
  name: bxkz5p09y-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bxkz5p09y-go 
